import './styles.css';

const $ = (selector) => document.querySelector(selector);
const today = new Date().toISOString();
const ratings = {
  Again: ['말을 시작하지 못했거나 정답을 먼저 봄', 0, -1],
  Hard: ['힌트를 사용했거나 8초 이상 걸림', 1, 0],
  Good: ['도움 없이 의미를 전달함', 3, 1],
  Easy: ['자연스럽게 말하고 후속 질문에도 대응함', 7, 1],
};
const seedCards = [
  { id:'seed-1', situation:'A coworker asks whether the current data is enough to make a decision.', prompt:'회의에서 동료가 현재 데이터만으로 결론을 내려도 되냐고 묻습니다. 정중하게 아직 이르다고 말하세요.', intent:'데이터가 아직 부족해서 결론 내리기 이르다고 말하고 싶었음', attempt:'It is early to make a conclusion because we need more data.', target:'I think it’s still too early to draw a conclusion because we don’t have enough data yet.', alternatives:['We probably need more data before drawing any conclusions.','I’d hold off on making a final call until we have more data.'], followUp:'What additional data do you think we need?', tag:'업무', level:1, dueAt:today, createdAt:today, history:[] },
  { id:'seed-2', situation:'Your team asks if the current project plan still works.', prompt:'상대방을 탓하지 않으면서 일정이 촉박해 보여 우선순위를 다시 정해야 할 것 같다고 말하세요.', intent:'일정이 좀 빡빡해 보여서 우선순위를 다시 정해야 할 것 같다.', attempt:'The schedule is very difficult, so we should change the priority.', target:'The schedule looks a little tight, so I think we may need to revisit our priorities.', alternatives:['This timeline feels a bit aggressive.','We may need to reprioritize a few things.'], followUp:'Which priorities would you revisit first?', tag:'업무', level:1, dueAt:today, createdAt:today, history:[] }
];
let state = { tab:'home', active:0, answer:'', revealed:false, repeat:false, cards: JSON.parse(localStorage.getItem('speaking-gap-cards') || 'null') || seedCards };
function persist(){ localStorage.setItem('speaking-gap-cards', JSON.stringify(state.cards)); }
function dueCards(){ return state.cards.filter((card) => new Date(card.dueAt) <= new Date()); }
function addDays(days){ const date = new Date(); date.setDate(date.getDate()+days); return date.toISOString(); }
function esc(value=''){ return value.replace(/[&<>"]/g, (m) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }
function generateCard(form){
  const text = `${form.situation} ${form.intent}`.toLowerCase();
  const data = text.includes('데이터') || text.includes('data');
  const schedule = text.includes('일정') || text.includes('schedule');
  return { id: crypto.randomUUID(), situation: data?'A coworker asks whether the current data is enough to make a decision.':schedule?'A teammate asks whether the current timeline still looks realistic.':form.situation || 'Someone asks for your opinion in a real conversation.', prompt: form.situation || form.intent, intent: form.intent, attempt: form.attempt, target: data?'I think it’s still too early to draw a conclusion because we don’t have enough data yet.':schedule?'The schedule looks a little tight, so I think we may need to revisit our priorities.':'I want to be careful about how I say this, but I think we should talk through it once more.', alternatives: data?['We probably need more data before drawing any conclusions.','I’d hold off until we have enough evidence.']:schedule?['This timeline feels a bit aggressive.','We may need to reprioritize a few things.']:['Could we revisit this before deciding?','I’m not fully comfortable moving forward yet.'], followUp: data?'What additional data do you think we need?':'What would you suggest we change first?', tag:form.tag, level:1, dueAt:today, createdAt:today, history:[] };
}
function shell(content){ $('#root').innerHTML = `<div class="app"><header><div><p class="eyebrow">Speaking Gap</p><h1>못 했던 말을 다음엔 바로 꺼내는 훈련</h1></div><button data-tab="save" class="primary">＋ 방금 못 한 말 저장</button></header><nav>${[['home','홈'],['review','오늘 복습'],['mission','실전 대화'],['library','표현 보관함']].map(([id,label])=>`<button data-tab="${id}" class="${state.tab===id?'on':''}">${label}</button>`).join('')}</nav>${content}</div>`; document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab; render();}); }
function render(){ const due=dueCards(); if(state.tab==='save') return renderSave(); if(state.tab==='review') return renderReview(); if(state.tab==='mission') return renderMission(due.length?due:state.cards); if(state.tab==='library') return renderLibrary(); shell(`<main class="grid"><section class="hero"><h2>오늘 복습할 말 ${due.length}개</h2><p>문장이 아니라 “그 상황에서 하고 싶었던 말”을 저장하고, 정답을 가린 채 다시 말합니다.</p><button data-tab="review" class="primary">🎙️ 오늘 복습 시작</button></section><section class="panel"><h2>⏰ 최근 저장한 못 한 말</h2>${state.cards.slice(0,3).map(c=>`<p>${esc(c.intent)}</p>`).join('')}</section><section class="panel"><h2>🔁 학습 루프</h2><ol><li>한국어로 즉시 저장</li><li>AI가 쓸 한 문장으로 정리</li><li>상황만 보고 말하기</li><li>피드백 후 반드시 다시 말하기</li></ol></section></main>`); }
function renderSave(){ shell(`<main><section class="panel"><h2>✨ 이걸 어떻게 말하지?</h2><label>어떤 상황이었나요?<textarea id="situation"></textarea></label><label>무슨 말을 하고 싶었나요?<textarea id="intent"></textarea></label><label>실제로 영어로 어떻게 말했나요? (선택)<textarea id="attempt"></textarea></label><label>태그<select id="tag"><option>업무</option><option>일상</option><option>여행</option><option>감정</option><option>의견</option></select></label><div id="draft"></div></section></main>`); ['situation','intent','attempt','tag'].forEach(id => $('#'+id).oninput = updateDraft); updateDraft(); }
function updateDraft(){ const form = {situation:$('#situation').value, intent:$('#intent').value, attempt:$('#attempt').value, tag:$('#tag').value}; if(!form.intent.trim()){ $('#draft').innerHTML=''; return; } const draft=generateCard(form); $('#draft').innerHTML=`<div class="recommend"><b>AI 추천 기본 표현</b><p>${esc(draft.target)}</p><small>대안: ${draft.alternatives.map(esc).join(' / ')}</small><button id="save-card" class="primary">내 기본 표현으로 저장</button></div>`; $('#save-card').onclick=()=>{state.cards=[draft,...state.cards]; persist(); state.tab='review'; render();}; }
function renderReview(){ const due=dueCards(); const card=due[state.active % Math.max(due.length,1)]; if(!card) return shell('<main><section class="panel"><h2>오늘 복습 완료</h2><p>새로운 “못 한 말”을 저장하거나 실전 대화 테스트를 해보세요.</p></section></main>'); shell(`<main><section class="review"><p class="eyebrow">상황 시뮬레이션</p><h2>${esc(card.prompt)}</h2><div class="timer">준비 5초 → 도움 없이 말하기</div><textarea id="answer" placeholder="음성 인식 결과가 여기에 들어옵니다. 지금은 직접 입력해 테스트하세요.">${esc(state.answer)}</textarea><button id="reveal">🎙️ 말하기 완료 / 피드백 보기</button><div id="feedback"></div></section></main>`); $('#answer').oninput=(e)=>state.answer=e.target.value; $('#reveal').onclick=()=>{state.revealed=true; showFeedback(card);}; if(state.revealed) showFeedback(card); }
function showFeedback(card){ const feedback=state.answer.length<20?'의미가 부족할 수 있어요. 핵심 이유와 결론을 함께 말해보세요.':'의미 전달 성공. 한 가지 자연스러운 표현만 고치면 더 좋아요.'; $('#feedback').innerHTML=`<div class="feedback"><b>${feedback}</b><p>추천 표현: ${esc(card.target)}</p><p>차이 한 가지: make a conclusion보다는 draw a conclusion이 더 자연스럽습니다.</p>${state.repeat?'<textarea placeholder="수정된 표현을 한 번 더 말한 결과"></textarea><div class="ratings">'+Object.keys(ratings).map(r=>`<button data-rate="${r}">${r}<small>${ratings[r][0]}</small></button>`).join('')+'</div>':'<button id="repeat" class="primary">수정된 문장 다시 말하기</button>'}</div>`; const repeat=$('#repeat'); if(repeat) repeat.onclick=()=>{state.repeat=true; showFeedback(card);}; document.querySelectorAll('[data-rate]').forEach(btn=>btn.onclick=()=>rate(card, btn.dataset.rate)); }
function rate(card, rating){ const [,days,delta]=ratings[rating]; state.cards=state.cards.map(c=>c.id===card.id?{...c, level:Math.max(1,c.level+delta), dueAt:addDays(days), history:[...c.history,{rating, answer:state.answer, at:new Date().toISOString()}]}:c); state.active++; state.answer=''; state.revealed=false; state.repeat=false; persist(); renderReview(); }
function renderMission(cards){ shell(`<main><section class="panel"><h2>💬 Targeted Conversation</h2><p>오늘 목표 표현 ${Math.min(cards.length,3)}개를 실제 대화 속에서 꺼내는 최종 테스트입니다.</p>${cards.slice(0,3).map((c,i)=>`<div class="mission"><b>AI ${i+1}: ${i===0?'Based on the current situation, should we decide today?':esc(c.followUp)}</b><p>목표 표현: ${esc(c.target)}</p></div>`).join('')}</section></main>`); }
function renderLibrary(){ shell(`<main><section class="panel"><h2>📚 표현 보관함</h2>${state.cards.map(c=>`<article class="item"><span>🏷️ ${esc(c.tag)}</span><h3>${esc(c.intent)}</h3><p>${esc(c.target)}</p><small>Level ${c.level} · Due ${new Date(c.dueAt).toLocaleDateString()}</small></article>`).join('')}</section></main>`); }
render();
